name: Terraform Workflow on Feature Branch

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  fmt-validate:
    name: Format And validate
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run terraform fmt check
        run: |
          terraform init
          terraform fmt -check -diff
          terraform validate
  scan-security:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        run: terraform init -input=false -backend=false
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
      - name: Comments On Pull Request
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [ fmt-validate, scan-security]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
 
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    steps:
      - run: echo "Pruebas unitarias sobre el codigo"
